routes/admin.py
from flask import Blueprint, render_template, abort, request, flash, redirect, url_for
from flask_login import LoginManager, UserMixin, login_user, logout_user, login_required

from database import KeyData
from config.admin import *


def create_admin_bp(app):
    admin_bp = Blueprint('admin_bp', __name__)

    db = KeyData(app)
    login_manager = LoginManager()
    login_manager.init_app(app)
    login_manager.login_view = 'admin_bp.login'
    login_manager.refresh_view = "admin_bp.login"
    login_manager.needs_refresh_message = (
        u"Session expired, please login again."
    )
    login_manager.needs_refresh_message_category = "warn"

    @login_manager.user_loader
    def load_user(user_id):
        if user_id == USERNAME:
            return User(user_id)
        return None

    class User(UserMixin):
        def __init__(self, user_id):
            self.id = user_id

        def get(self):
            return self.id

    @admin_bp.route('/login', methods=['GET', 'POST'])
    def login():
        if request.method == 'POST':
            username = request.form.get('username')
            password = request.form.get('password')
            if username == USERNAME and password == PASSWORD:
                user = User(USERNAME)
                login_user(user)
                return redirect(url_for('admin_bp.main'))
            flash('Invalid username or password!', 'warn')

        return render_template('loginPage.html')

    @admin_bp.route('/logout')
    @login_required
    def logout():
        logout_user()
        return redirect(url_for('admin_bp.login'))

    @admin_bp.route('/')
    @login_required
    def main():
        data = db.get()
        return render_template('mainPage.html', data=data)

    @admin_bp.route('/moodle', methods=['GET', 'POST'])
    @login_required
    def create():
        if request.method == 'POST':
            name = request.form.get('name')
            moodle = request.form.get('moodle')
            wstoken = request.form.get('wstoken')
            key = request.form.get('key')

            if moodle[-1] == '/':
                moodle = moodle[:-1]

            if db.get_by_name(name):
                flash('Name exist!', 'warn')
            elif db.get_data(moodle):
                flash('Moodle exist!', 'warn')
            elif db.get_by_key(key):
                flash('API Key exist!', 'warn')
            elif db.create(
                name=name,
                moodle=moodle,
                wstoken=wstoken,
                key=key
            ):
                flash('Success!', 'info')
                return redirect(url_for('admin_bp.update', name=name))
            else:
                flash('Failed to create!', 'error')
        return render_template('addPage.html')

    @admin_bp.route('/moodle/<name>', methods=['GET', 'POST'])
    @login_required
    def update(name):
        if request.method == 'POST':
            moodle = request.form.get('moodle')
            wstoken = request.form.get('wstoken')
            key = request.form.get('key')
            current = db.get_by_name(name)

            if moodle != current['moodle'] and db.get_data(moodle):
                flash('Moodle exist!', 'warn')
            elif key != current['key'] and db.get_by_key(key):
                flash('API Key exist!', 'warn')
            elif db.update(
                name=name,
                moodle=moodle,
                wstoken=wstoken,
                key=key
            ):
                flash('Updated!', 'info')
            else:
                flash('Failed to update!', 'error')

        data = db.get_by_name(name)
        if not data:
            abort(404)
        return render_template('editPage.html', data=data)

    @admin_bp.route('/moodle/<name>/remove', methods=['POST'])
    @login_required
    def remove(name):
        if db.remove(name):
            flash(f'Removed {name}!', 'info')
            return redirect(url_for('admin_bp.main'))
        else:
            flash('Failed to remove!', 'error')
            return redirect(url_for('admin_bp.update', name=name))

    @admin_bp.route('/search')
    @login_required
    def search():
        keyword = request.args.get('keyword')
        data = db.search(keyword)
        flash(f'{len(data)} results', 'info')
        return render_template('mainPage.html', data=data)

    return admin_bp

templates/addPage.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.83.1">
  <title>Admin Site</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sidebars/">



  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="/static/styles/sidebars.css" rel="stylesheet">
</head>

<body>

  <main>

    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 100%;height:100vh;">
      <p class="logo">FIT@HCMUS</p>
      <a href="{{ url_for('admin_bp.main') }}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-anchor"><circle cx="12" cy="5" r="3"/><line x1="12" y1="22" x2="12" y2="8"/><path d="M5 12H2a10 10 0 0 0 20 0h-3"/></svg>
                &nbsp; &nbsp;<span class="fs-4"> Moodle</span>
      </a>
      <hr>
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
            <a href="{{ url_for('admin_bp.main') }}" class="nav-link " aria-current="page">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>
                Home
            </a>
            <a href="{{ url_for('admin_bp.create') }}" class="nav-link active" aria-current="page">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-square"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>
                Add
            </a>
        </li>
    </ul>
      <hr>
      <div class="dropdown">
        <a href="{{ url_for('admin_bp.logout') }}" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
          id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <strong>{{ current_user.id}}</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">

          <li><a class="dropdown-item" href="{{ url_for('admin_bp.logout') }}">Sign out</a></li>
        </ul>
      </div>
    </div>

  </main>
  <div class="container">
    <div style="display: flex; justify-content: space-between; margin: 1.5rem 0;">
      <div>
        <h3>Add A Moodle: </h3>
      </div>
      <a href="{{ url_for('admin_bp.main') }}" style="
        text-decoration: none;">
        <h3 type="button" class="btn btn-outline-primary">Back home</h3>
      </a>
    </div>
    <hr class="myline">

        <div>
          {% with msg = get_flashed_messages(category_filter=["warn"])[-1] %}
            {% if msg %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
          {% endwith %}
          {% with msg = get_flashed_messages(category_filter=["error"])[-1] %}
            {% if msg %}
            <div class="alert alert-danger alert-dismissible fade show" role="alert">
                {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
          {% endwith %}
        </div>

    <form class="form-show" action="{{ url_for('admin_bp.create') }}" method="post">
      <div class="mb-3">
        <label for="name" class="form-label">Name</label>
        <div style="display:flex">
          <input placeholder="moodle" required type="text" class="form-control" id="name" name="name">
        </div>
      </div>
      <div class="mb-3">
        <label for="moodle" class="form-label">Moodle URL</label>
        <div style="display:flex">
          <input placeholder="https://moodle.com" required type="text" class="form-control" id="moodle" name="moodle">
        </div>
      </div>
      <div class="mb-3">
        <label for="wstoken" class="form-label">WSToken</label>
        <div style="display:flex">
          <input required type="text" class="form-control" id="wstoken" name="wstoken">
        </div>
      </div>
      <div class="mb-3">
        <label for="key" class="form-label">API Key</label>
        <div style="display:flex">
          <input required type="text" class="form-control" id="key" name="key">
        </div>
      </div>

      <div class="mb-3 form-check">
        <input required type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Confirm</label>
      </div>
      <button type="submit" class="btn btn-primary">Submit</button>

    </form>
  </div>
  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
    crossorigin="anonymous"></script>
  <script>
    /* global bootstrap: false */
    (function () {
      'use strict'
      var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
      tooltipTriggerList.forEach(function (tooltipTriggerEl) {
        new bootstrap.Tooltip(tooltipTriggerEl)
      })
    })()

  </script>
</body>

</html>

templates/editPage.html
<!doctype html>
<html lang="en">

<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width, initial-scale=1">
  <meta name="description" content="">
  <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
  <meta name="generator" content="Hugo 0.83.1">
  <title>Admin Site</title>

  <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sidebars/">



  <!-- Bootstrap core CSS -->
  <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
    integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

  <style>
    .bd-placeholder-img {
      font-size: 1.125rem;
      text-anchor: middle;
      -webkit-user-select: none;
      -moz-user-select: none;
      user-select: none;
    }

    @media (min-width: 768px) {
      .bd-placeholder-img-lg {
        font-size: 3.5rem;
      }
    }
  </style>


  <!-- Custom styles for this template -->
  <link href="/static/styles/sidebars.css" rel="stylesheet">
</head>

<body>

  <main>
    <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 100%;height:100vh;">
      <p class="logo">FIT@HCMUS</p>
      <a href="{{ url_for('admin_bp.main') }}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
          stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
          class="feather feather-anchor">
          <circle cx="12" cy="5" r="3" />
          <line x1="12" y1="22" x2="12" y2="8" />
          <path d="M5 12H2a10 10 0 0 0 20 0h-3" />
        </svg>
        &nbsp; &nbsp;<span class="fs-4"> Moodle</span>
      </a>
      <hr>
      <ul class="nav nav-pills flex-column mb-auto">
        <li class="nav-item">
          <a href="{{ url_for('admin_bp.main') }}" class="nav-link" aria-current="page">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
              stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
              class="feather feather-home">
              <path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z" />
              <polyline points="9 22 9 12 15 12 15 22" />
            </svg>
            Home
          </a>
          <a href="{{ url_for('admin_bp.create') }}" class="nav-link" aria-current="page">
            <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none"
              stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round"
              class="feather feather-plus-square">
              <rect x="3" y="3" width="18" height="18" rx="2" ry="2" />
              <line x1="12" y1="8" x2="12" y2="16" />
              <line x1="8" y1="12" x2="16" y2="12" />
            </svg>
            Add
          </a>
        </li>
      </ul>
      <hr>
      <div class="dropdown">
        <a href="{{ url_for('admin_bp.logout') }}" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
          id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
          <strong>{{ current_user.id }}</strong>
        </a>
        <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">

          <li><a class="dropdown-item" href="{{ url_for('admin_bp.logout') }}">Sign out</a></li>
        </ul>
      </div>
    </div>

  </main>
  <div class="container">
    <div>
      {% with msg = get_flashed_messages(category_filter=["info"])[-1] %}
        {% if msg %}
        <div class="alert alert-success alert-dismissible fade show" role="alert">
            {{msg}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
      {% endwith %}
      {% with msg = get_flashed_messages(category_filter=["warn"])[-1] %}
        {% if msg %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert">
            {{msg}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
      {% endwith %}
      {% with msg = get_flashed_messages(category_filter=["error"])[-1] %}
        {% if msg %}
        <div class="alert alert-danger alert-dismissible fade show" role="alert">
            {{msg}}
            <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
        </div>
        {% endif %}
      {% endwith %}
    </div>

    <div style="display: flex; justify-content: space-between; margin: 1.5rem 0;">
      <div>
        <h5>Edit Page: </h5>
        <h3>{{ data.name }}</h3>
      </div>
      <a href="{{ url_for('admin_bp.main') }}" style="
        text-decoration: none;">
        <h3 type="button" class="btn btn-outline-primary">Back home</h3>
      </a>
    </div>
    <hr class="myline">
    <form class="form-show" action="{{ url_for('admin_bp.update', name=data.name) }}" method="post">
      <div class="mb-3">
        <label for="moodle" class="form-label">Moodle URL</label>
        <div style="display:flex">
          <input placeholder="https://moodle.com" value="{{data.moodle}}" style="margin-right:10px;display:flex" type="text" class="form-control" id="moodle" name="moodle">
        </div>
      </div>
      <div class="mb-3">
        <label for="wstoken" class="form-label">WSToken</label>
        <div style="display:flex">
          <input value="{{data.wstoken}}" style="margin-right:10px;display:flex" type="text" class="form-control" id="wstoken" name="wstoken">
        </div>
      </div>
      <div class="mb-3">
        <label for="key" class="form-label">API Key</label>
        <div style="display:flex">
          <input value="{{data.key}}" style="margin-right:10px;display:flex" type="text" class="form-control" id="key" name="key">
        </div>
      </div>
      <div class="mb-3 form-check">
        <input required type="checkbox" class="form-check-input" id="exampleCheck1">
        <label class="form-check-label" for="exampleCheck1">Confirm</label>
      </div>
      <button type="submit" class="btn btn-primary">Update Information</button>
      <button type="button" class="btn btn-danger ms-3" data-bs-toggle="modal" data-bs-target="#exampleModal">Remove Moodle</button>
      <div class="modal fade" id="exampleModal" tabindex="-1" aria-labelledby="exampleModalLabel" aria-hidden="true">
        <div class="modal-dialog">
          <div class="modal-content">
            <div class="modal-header">
              <h5 class="modal-title" id="exampleModalLabel">Are you sure about deleting the moodle?</h5>
              <button type="button" class="btn-close" data-bs-dismiss="modal" aria-label="Close"></button>
            </div>
            <div class="modal-body">
              This will make break some system
            </div>
            <div class="modal-footer">
              <button type="button" class="btn btn-secondary" data-bs-dismiss="modal">Close</button>
              <button id="buttondelete" onclick="functionClickDelete()" type="button"
                class="btn btn-primary">Confirm</button>
            </div>
          </div>
        </div>
      </div>
    </form>
  </div>

  <form action="{{ url_for('admin_bp.remove', name=data.name) }}" method="POST" id="formdelete"></form>

  <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
    integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
    crossorigin="anonymous"></script>
  <script>
    function functionClickDelete() {
      document.getElementById("formdelete").submit();
    }
  </script>
  <script>
    /* global bootstrap: false */
    (function () {
      'use strict'
      var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
      tooltipTriggerList.forEach(function (tooltipTriggerEl) {
        new bootstrap.Tooltip(tooltipTriggerEl)
      })
    })()

  </script>
</body>

</html>

templates/mainPage.html
<!doctype html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <meta name="description" content="">
    <meta name="author" content="Mark Otto, Jacob Thornton, and Bootstrap contributors">
    <meta name="generator" content="Hugo 0.83.1">
    <title>Admin Site</title>

    <link rel="canonical" href="https://getbootstrap.com/docs/5.0/examples/sidebars/">



    <!-- Bootstrap core CSS -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/css/bootstrap.min.css" rel="stylesheet"
        integrity="sha384-+0n0xVW2eSR5OomGNYDnhzAbDsOXxcvSN1TPprVMTNDbiYZCxYbOOl7+AMvyTG2x" crossorigin="anonymous">

    <style>
        .bd-placeholder-img {
            font-size: 1.125rem;
            text-anchor: middle;
            -webkit-user-select: none;
            -moz-user-select: none;
            user-select: none;
        }

        @media (min-width: 768px) {
            .bd-placeholder-img-lg {
                font-size: 3.5rem;
            }
        }

        div .input-group {
            width: 50%;
            margin: 0 auto;
        }
    </style>


    <!-- Custom styles for this template -->
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/4.7.0/css/font-awesome.css" integrity="sha512-5A8nwdMOWrSz20fDsjczgUidUBR8liPYU+WymTZP1lmY9G6Oc7HlZv156XqnsgNUzTyMefFTcsFH/tnJE/+xBg==" />
    <link href="/static/styles/sidebars.css" rel="stylesheet">
</head>

<body>

    <main>

        <div class="d-flex flex-column flex-shrink-0 p-3 text-white bg-dark" style="width: 100%;height:100vh;">
            <p class="logo">FIT@HCMUS</p>
            <a href="{{ url_for('admin_bp.main') }}" class="d-flex align-items-center mb-3 mb-md-0 me-md-auto text-white text-decoration-none">
                <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-anchor"><circle cx="12" cy="5" r="3"/><line x1="12" y1="22" x2="12" y2="8"/><path d="M5 12H2a10 10 0 0 0 20 0h-3"/></svg>
                &nbsp; &nbsp;<span class="fs-4"> Moodle</span>
            </a>
            <hr>
            <ul class="nav nav-pills flex-column mb-auto">
                <li class="nav-item">
                    <a href="{{ url_for('admin_bp.main') }}" class="nav-link active" aria-current="page">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-home"><path d="M3 9l9-7 9 7v11a2 2 0 0 1-2 2H5a2 2 0 0 1-2-2z"/><polyline points="9 22 9 12 15 12 15 22"/></svg>
                        Home
                    </a>
                    <a href="{{ url_for('admin_bp.create') }}" class="nav-link" aria-current="page">
                        <svg xmlns="http://www.w3.org/2000/svg" width="24" height="24" viewBox="0 0 24 24" fill="none" stroke="currentColor" stroke-width="2" stroke-linecap="round" stroke-linejoin="round" class="feather feather-plus-square"><rect x="3" y="3" width="18" height="18" rx="2" ry="2"/><line x1="12" y1="8" x2="12" y2="16"/><line x1="8" y1="12" x2="16" y2="12"/></svg>
                        Add
                    </a>
                </li>
            </ul>
            <hr>
            <div class="dropdown">
                <a href="{{ url_for('admin_bp.logout') }}" class="d-flex align-items-center text-white text-decoration-none dropdown-toggle"
                    id="dropdownUser1" data-bs-toggle="dropdown" aria-expanded="false">
                    <strong>{{ current_user.id }}</strong>
                </a>
                <ul class="dropdown-menu dropdown-menu-dark text-small shadow" aria-labelledby="dropdownUser1">

                    <li><a class="dropdown-item" href="{{ url_for('admin_bp.logout') }}">Sign out</a></li>
                </ul>
            </div>
        </div>
    </main>
    <div class="container">
        <div style="display: flex; justify-content: space-between; margin: 1.5rem 0;">
            <div>
                <h3>HOME</h3>
            </div>
            <button type="button" class="btn btn-primary"><a href="{{ url_for('admin_bp.create') }}">Add A Moodle</a></button>
        </div>
        <hr class="myline">

        <div>
          {% with msg = get_flashed_messages(category_filter=["info"])[-1] %}
            {% if msg %}
            <div class="alert alert-success alert-dismissible fade show" role="alert">
                {{msg}}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
            {% endif %}
          {% endwith %}
        </div>

        <form class="input-group mb-5 mt-5" action="{{ url_for('admin_bp.search', keyword=keyword) }}">
            <span class="input-group-text" id="basic-addon1"><svg xmlns="http://www.w3.org/2000/svg" width="16"
                    height="16" fill="currentColor" class="bi bi-search" viewBox="0 0 16 16">
                    <path
                        d="M11.742 10.344a6.5 6.5 0 1 0-1.397 1.398h-.001c.03.04.062.078.098.115l3.85 3.85a1 1 0 0 0 1.415-1.414l-3.85-3.85a1.007 1.007 0 0 0-.115-.1zM12 6.5a5.5 5.5 0 1 1-11 0 5.5 5.5 0 0 1 11 0z" />
                </svg></span>
            <input type="text" class="form-control" placeholder="Search Moodle" aria-label="url"
                aria-describedby="basic-addon1" name="keyword" required>
            <button class="btn btn-primary" type="submit">Search</button>
        </form>
        {% if data %}
        <table class="table">
            <thead>
                <tr>
                    <th scope="col">#</th>
                    <th scope="col">Name</th>
                    <th scope="col">Moodle URL</th>
                    <th>WSToken</th>
                    <th scope="col">API Key</th>
                    <th scope="col"></th>
                </tr>
            </thead>
            <tbody>
                {% for i in range(data | length) %}
                <tr>
                    <th scope="row">{{i}}</th>
                    <td>{{data[i].name}}</td>
                    <td>{{data[i].moodle}}</td>
                    <td>{{data[i].wstoken}}</td>
                    <td>{{data[i].key}}</td>
                    <td>
                        <button type="button" class="btn btn-secondary">
                            <a href="{{ url_for('admin_bp.update', name=data[i].name) }}">Edit</a>
                        </button>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
        {% endif %}
    </div>

    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.1/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-gtEjrD/SeCtmISkJkNUaaKMoLD0//ElJ19smozuHV6z3Iehds+3Ulb9Bn9Plx0x4"
        crossorigin="anonymous"></script>

    <script>
        /* global bootstrap: false */
        (function () {
            'use strict'
            var tooltipTriggerList = [].slice.call(document.querySelectorAll('[data-bs-toggle="tooltip"]'))
            tooltipTriggerList.forEach(function (tooltipTriggerEl) {
                new bootstrap.Tooltip(tooltipTriggerEl)
            })
        })()

    </script>
</body>

</html>